# Use Ubuntu 'trusty' distribution
sudo: required

services:
  - docker

before_script:
  - docker build . -t stix-pattern

script:
  - docker run -it --rm stix-pattern pipenv run coverage
  - docker run -it --rm stix-pattern pipenv run codestyle
